Add userland stacks and threads commands
delphix/sdb pull request #321
Opened 2023-03-20 21:27 UTC by pcd1193182

Now that the stacks and threads commands have been properly separated into the kernel module, we can write a userland implementation of these commands.  These implementations are heavily based on the originals, but using the generic drgn API that doesn't assume it can access the thread's object parameter. As a result, we have to lose the `module` and `state` filters on the stacks.

2023-03-21 15:30 UTC, ahrens approved these changes
can we add a test case for this?

2023-03-21 17:15 UTC, sdimitro requested changes

2023-03-21 17:15 UTC, sdimitro commented on sdb/commands/ustacks.py
> +    TODO
Leftover TODO

2023-03-21 17:15 UTC, sdimitro commented on sdb/commands/ustacks.py
> +
Per your commit description we don't implement `-m` correct?

2023-03-21 17:15 UTC, sdimitro commented on sdb/commands/ustacks.py
> +                              ret_from_fork+0x35
Can we add some test examples here?

2023-03-21 17:15 UTC, sdimitro commented on sdb/commands/ustacks.py
> +            # transitioned from running to some other state.
That could be something worth mentioning the `man/help` message above; i.e. "the running thread may not come up on live processes"

BTW is that the case for core dumps too?

2023-03-21 17:15 UTC, sdimitro commented on sdb/commands/ustacks.py
> +                          entry_SYSCALL_64+0x94
New example here?

2023-03-22 16:27 UTC, sdimitro approved these changes

2023-03-22 16:30 UTC, sdimitro commented
@ahrens @pcd1193182

In terms of testing we could add a userland core dump to our test suite the same way we have kernel ones but the testing infrastructure will need to be adjusted a bit more. I can slowly start working on this. In the meantime I'm good with merging this.

2023-03-22 18:02 UTC, merged